### ISSUE TITLE
Error!! [rickroll.mp4 not found]

### ISSUE THREAD

**Issue by athrvvvv** [Dhravya/rickroll-maker#2]
### I have literally tried everything and I have from all steps mention in the README file but I get this error:-
![Screenshot 2022-04-10 161642](https://user-images.githubusercontent.com/98272709/162614546-2e2ea485-ef89-40c4-a6d5-e17b084348a4.png)

### I have made an video of this problem:-
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Dhravya** [comment]
AHAH really!!!! I’m not falling for that 🤣  I recognize the rickroll link From: athrvSent: Sunday, April 10, 2022 4:19 PMTo: Dhravya/rickroll-makerCc: SubscribedSubject: [Dhravya/rickroll-maker] Error!! [rickroll.mp4 not found] (Issue #2) I have literally tried everything and I have from all steps mention in the README file but I get this error:-I have made an video of this problem:-https://www.youtube.com/watch?v=dQw4w9WgXcQ—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Dhravya** [comment]
Lmaoooo I recognise the rickroll link! Not falling for that haha!

Anyways, you need to pass the rickroll.mp4 video path, that's the reason it's not working. I didn't include it in the repo because of copyright issues

**Comment by athrvvvv** [comment]
Hahah good 
but at this time, I did pass the rickroll.mp4 video path but now also it didn't work :(
I think you should check the code once
See:-
![Screenshot 2022-04-10 170713](https://user-images.githubusercontent.com/98272709/162616244-fbd35e6d-056e-4f2a-8d57-386014c65df1.png)

**Comment by techguy16** [comment]
You will need to cd into the src directory and run it from there.
You do not use the rickroll file as the input, you use another video you want to make a rickroll

**Comment by Dhravya** [comment]
actually, I had removed the rickroll.mp4 earlier, so you'll have to add one yourself

**Comment by athrvvvv** [comment]
just downloaded previous c5e4d75326e0de270819e34d2990de2eda5302de commit version... works fine. thanks @techguy16 

@Dhravya as said "you did'nt include rickroll video in" https://github.com/Dhravya/rickroll-maker/issues/2#issuecomment-1094244446https://github.com/Dhravya/rickroll-maker/issues/2#issuecomment-1094244446 because of **copyright** issues. Remember one thing, if you are earning from this repository than you will face copyright issues, else everything will be fine.
